package globals

var WebReloadChan = make(chan bool)
var MetricsReloadChan = make(chan bool)
var DatabaseReloadChan = make(chan bool)
var DatastoresReloadChan = make(chan bool)
var RecurringTasksReloadChan = make(chan bool)
var AccessTokenReloadChan = make(chan bool)
var CacheReplaceChan = make(chan bool)
var PluginReloadChan = make(chan bool)
var PoolReloadChan = make(chan bool)
var ErrorCacheReloadChan = make(chan bool)
var MatrixCachesReloadChan = make(chan bool)
var PGOReloadChan = make(chan bool)
var BucketsReloadChan = make(chan bool)
