package main

import (
	"bytes"
	"compress/gzip"
	"encoding/hex"
	"flag"
	"fmt"
	"io/ioutil"
	"path"

	"github.com/turt2live/matrix-media-repo/common/config"
)

func main() {
	migrationsPath := flag.String("migrations", config.DefaultMigrationsPath, "The absolute path for the migrations folder")
	templatesPath := flag.String("templates", config.DefaultTemplatesPath, "The absolute path for the templates folder")
	assetsPath := flag.String("assets", config.DefaultAssetsPath, "The absolute path for the assets folder")
	outputFile := flag.String("output", "./common/assets/assets.bin.go", "The output Go file to dump the files into")
	flag.Parse()

	fmt.Println("Reading migrations into memory...")
	migrations := readDir(*migrationsPath, "migrations")
	templates := readDir(*templatesPath, "templates")
	assets := readDir(*assetsPath, "assets")

	fileMap := make(map[string][]byte)
	for k, v := range migrations {
		fileMap[k] = v
	}
	for k, v := range templates {
		fileMap[k] = v
	}
	for k, v := range assets {
		fileMap[k] = v
	}

	fmt.Println("Writing assets go file")
	str := "package " + path.Base(path.Dir(*outputFile)) + "\n\n"
	str += "// !! THIS FILE IS AUTOMATICALLY GENERATED. You can edit it, but it will be overwritten over time.\n\n"
	str += "var compressedFiles = map[string]string{\n"
	for f, b := range fileMap {
		b64 := hex.EncodeToString(b)
		str += fmt.Sprintf("\t\"%s\": \"%s\",\n", f, b64)
	}
	str += "}\n"
	err := ioutil.WriteFile(*outputFile, []byte(str), 0644)
	if err != nil {
		panic(err)
	}

	fmt.Println("Done")
}

func readDir(dir string, pathName string) map[string][]byte {
	fileMap := make(map[string][]byte)
	files, err := ioutil.ReadDir(dir)
	if err != nil {
		panic(err)
	}
	for _, f := range files {
		fname := path.Join(dir, f.Name())
		fmt.Println("Reading ", fname)

		b, err := ioutil.ReadFile(fname)
		if err != nil {
			panic(err)
		}

		// Compress the file
		fmt.Println("Compressing ", fname)
		out := &bytes.Buffer{}
		gw, err := gzip.NewWriterLevel(out, gzip.BestCompression)
		if err != nil {
			panic(err)
		}
		_, _ = gw.Write(b)
		_ = gw.Close()

		fileMap[path.Join(pathName, f.Name())] = out.Bytes()
	}
	return fileMap
}
