{
 "title": "Media Repo Example Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "HTTP Requsts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(media_http_requests_total[2m])",
     "legendFormat": "{{host}}: {{method}} {{action}}"
    },
    {
     "expr": "rate(media_invalid_http_requests_total[2m])",
     "legendFormat": "Invalid Host: {{method}} {{action}}"
    }
   ]
  },
  {
   "title": "HTTP Responses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(media_http_responses_total[2m])",
     "legendFormat": "{{host}}: {{method}} {{action}} {{statusCode}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "memory usage (alloc)" },
    { "expr": "go_memstats_sys_bytes", "legendFormat": "memory usage (sys)" }
   ]
  },
  {
   "title": "Cache Size (Bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "media_cache_num_bytes_used", "legendFormat": "size of cache: {{cache}}" },
    {
     "expr": "media_cache_num_live_bytes_used",
     "legendFormat": "live size of cache: {{cache}}"
    }
   ]
  },
  {
   "title": "Cache Size (# of items)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "media_cache_num_items", "legendFormat": "items in cache: {{cache}}" },
    { "expr": "media_cache_num_live_items", "legendFormat": "live items in cache: {{cache}}" }
   ]
  },
  {
   "title": "Cache Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(media_cache_hits_total[2m])",
     "legendFormat": "hits in {{cache}}"
    },
    {
     "expr": "rate(media_cache_misses_total[2m])",
     "legendFormat": "misses in {{cache}}"
    },
    {
     "expr": "rate(media_cache_evictions_total[2m])",
     "legendFormat": "evictions due to {{reason}} in {{cache}}"
    }
   ]
  },
  {
   "title": "Thumbnail Generation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(media_thumbnails_generated_total[2m])",
     "legendFormat": "{{origin}} {{width}}x{{height}} {{method}} animated={{animated}}"
    }
   ]
  },
  {
   "title": "Resource Handling",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(media_downloaded_total[2m])",
     "legendFormat": "downloads from {{origin}}"
    },
    {
     "expr": "rate(media_url_previews_generated_total[2m])",
     "legendFormat": "preview with engine: {{type}}"
    }
   ]
  }
 ]
}